-- 育人过程文档管理数据库表结构
-- 创建时间：2023-04-10
-- 创建者：AI助手

-- 教学大纲表
CREATE TABLE IF NOT EXISTS `ed_syllabus` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '大纲ID',
  `course_id` bigint(20) NOT NULL COMMENT '课程ID',
  `course_code` varchar(50) DEFAULT NULL COMMENT '课程代码',
  `course_name` varchar(100) DEFAULT NULL COMMENT '课程名称',
  `version` varchar(20) DEFAULT NULL COMMENT '版本号',
  `semester` varchar(20) DEFAULT NULL COMMENT '学期',
  `teacher_id` bigint(20) DEFAULT NULL COMMENT '教师ID',
  `teacher_name` varchar(50) DEFAULT NULL COMMENT '教师姓名',
  `dept_id` bigint(20) DEFAULT NULL COMMENT '院系ID',
  `teaching_objectives` text COMMENT '教学目标',
  `teaching_content` text COMMENT '教学内容',
  `teaching_methods` text COMMENT '教学方法',
  `assessment_methods` text COMMENT '考核方法',
  `textbooks` text COMMENT '教材',
  `references` text COMMENT '参考资料',
  `teaching_schedule` text COMMENT '教学进度计划',
  `practice_arrangement` text COMMENT '实践环节安排',
  `status` tinyint(1) DEFAULT '0' COMMENT '状态：0-草稿，1-审核中，2-已通过，3-已驳回',
  `approval_id` bigint(20) DEFAULT NULL COMMENT '审批ID',
  `creator` varchar(50) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(50) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_teacher_id` (`teacher_id`),
  KEY `idx_dept_id` (`dept_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='教学大纲表';

-- 教案表
CREATE TABLE IF NOT EXISTS `ed_teaching_plan` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '教案ID',
  `syllabus_id` bigint(20) DEFAULT NULL COMMENT '大纲ID',
  `course_id` bigint(20) NOT NULL COMMENT '课程ID',
  `course_code` varchar(50) DEFAULT NULL COMMENT '课程代码',
  `course_name` varchar(100) DEFAULT NULL COMMENT '课程名称',
  `semester` varchar(20) DEFAULT NULL COMMENT '学期',
  `teacher_id` bigint(20) DEFAULT NULL COMMENT '教师ID',
  `teacher_name` varchar(50) DEFAULT NULL COMMENT '教师姓名',
  `dept_id` bigint(20) DEFAULT NULL COMMENT '院系ID',
  `week` int(11) DEFAULT NULL COMMENT '教学周次',
  `class_hour` int(11) DEFAULT NULL COMMENT '课时',
  `title` varchar(200) NOT NULL COMMENT '教案标题',
  `content` text COMMENT '教案内容',
  `teaching_objectives` text COMMENT '教学目标',
  `teaching_methods` text COMMENT '教学方法',
  `teaching_aids` text COMMENT '教学辅助手段',
  `key_points` text COMMENT '教学重点',
  `difficult_points` text COMMENT '教学难点',
  `assignments` text COMMENT '作业安排',
  `reflection` text COMMENT '教学反思',
  `status` tinyint(1) DEFAULT '0' COMMENT '状态：0-草稿，1-已完成',
  `creator` varchar(50) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(50) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_syllabus_id` (`syllabus_id`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_teacher_id` (`teacher_id`),
  KEY `idx_dept_id` (`dept_id`),
  KEY `idx_semester_week` (`semester`,`week`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='教案表';

-- 教案模板表
CREATE TABLE IF NOT EXISTS `ed_teaching_plan_template` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '模板ID',
  `name` varchar(100) NOT NULL COMMENT '模板名称',
  `category` varchar(50) DEFAULT NULL COMMENT '模板分类',
  `description` varchar(500) DEFAULT NULL COMMENT '模板描述',
  `content` text COMMENT '模板内容',
  `fields` text COMMENT '字段设置(JSON)',
  `is_default` tinyint(1) DEFAULT '0' COMMENT '是否默认：0-否，1-是',
  `usage_count` int(11) DEFAULT '0' COMMENT '使用次数',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态：0-禁用，1-正常',
  `creator` varchar(50) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(50) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_category` (`category`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='教案模板表';

-- 文件上传记录表
CREATE TABLE IF NOT EXISTS `ed_file_upload` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '上传ID',
  `file_name` varchar(200) NOT NULL COMMENT '文件名',
  `original_name` varchar(200) DEFAULT NULL COMMENT '原始文件名',
  `file_path` varchar(500) NOT NULL COMMENT '文件路径',
  `file_url` varchar(500) DEFAULT NULL COMMENT '文件URL',
  `file_type` varchar(50) DEFAULT NULL COMMENT '文件类型',
  `file_size` bigint(20) DEFAULT NULL COMMENT '文件大小(字节)',
  `md5` varchar(32) DEFAULT NULL COMMENT '文件MD5',
  `content_type` varchar(100) DEFAULT NULL COMMENT '文件内容类型',
  `module` varchar(50) DEFAULT NULL COMMENT '所属模块',
  `module_id` bigint(20) DEFAULT NULL COMMENT '模块记录ID',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态：0-无效，1-有效',
  `creator` varchar(50) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_module_id` (`module`,`module_id`),
  KEY `idx_file_md5` (`md5`),
  KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文件上传记录表';

-- 试卷表
CREATE TABLE IF NOT EXISTS `ed_exam_paper` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '试卷ID',
  `name` varchar(200) NOT NULL COMMENT '试卷名称',
  `course_id` bigint(20) NOT NULL COMMENT '课程ID',
  `course_code` varchar(50) DEFAULT NULL COMMENT '课程代码',
  `course_name` varchar(100) DEFAULT NULL COMMENT '课程名称',
  `semester` varchar(20) DEFAULT NULL COMMENT '学期',
  `exam_type` varchar(20) DEFAULT NULL COMMENT '考试类型：期中、期末、补考',
  `paper_type` varchar(20) DEFAULT NULL COMMENT '试卷类型：A卷、B卷',
  `teacher_id` bigint(20) DEFAULT NULL COMMENT '出题教师ID',
  `teacher_name` varchar(50) DEFAULT NULL COMMENT '出题教师姓名',
  `dept_id` bigint(20) DEFAULT NULL COMMENT '院系ID',
  `total_score` int(11) DEFAULT '100' COMMENT '总分',
  `passing_score` int(11) DEFAULT '60' COMMENT '及格分数',
  `exam_duration` int(11) DEFAULT '120' COMMENT '考试时长(分钟)',
  `is_template` tinyint(1) DEFAULT '0' COMMENT '是否模板：0-否，1-是',
  `content` text COMMENT '试卷内容(JSON)',
  `answer` text COMMENT '参考答案(JSON)',
  `scoring_criteria` text COMMENT '评分标准(JSON)',
  `status` tinyint(1) DEFAULT '0' COMMENT '状态：0-草稿，1-审核中，2-已通过，3-已驳回',
  `approval_id` bigint(20) DEFAULT NULL COMMENT '审批ID',
  `creator` varchar(50) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(50) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_teacher_id` (`teacher_id`),
  KEY `idx_dept_id` (`dept_id`),
  KEY `idx_status` (`status`),
  KEY `idx_semester` (`semester`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='试卷表';

-- 题库表
CREATE TABLE IF NOT EXISTS `ed_question_bank` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '题目ID',
  `question_type` varchar(20) NOT NULL COMMENT '题目类型：单选题、多选题、判断题、填空题、简答题等',
  `course_id` bigint(20) DEFAULT NULL COMMENT '课程ID',
  `knowledge_point_id` bigint(20) DEFAULT NULL COMMENT '知识点ID',
  `title` text NOT NULL COMMENT '题目标题',
  `options` text COMMENT '选项(JSON)',
  `answer` text COMMENT '答案',
  `analysis` text COMMENT '解析',
  `difficulty` int(11) DEFAULT '3' COMMENT '难度：1-5',
  `score` decimal(10,2) DEFAULT '0.00' COMMENT '分值',
  `tags` varchar(500) DEFAULT NULL COMMENT '标签',
  `category` varchar(50) DEFAULT NULL COMMENT '分类',
  `usage_count` int(11) DEFAULT '0' COMMENT '使用次数',
  `correct_count` int(11) DEFAULT '0' COMMENT '正确次数',
  `creator` varchar(50) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(50) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_knowledge_point_id` (`knowledge_point_id`),
  KEY `idx_question_type` (`question_type`),
  KEY `idx_difficulty` (`difficulty`),
  KEY `idx_category` (`category`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='题库表';

-- 实验指导书表
CREATE TABLE IF NOT EXISTS `ed_experiment_guide` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '指导书ID',
  `name` varchar(200) NOT NULL COMMENT '实验名称',
  `course_id` bigint(20) NOT NULL COMMENT '课程ID',
  `course_code` varchar(50) DEFAULT NULL COMMENT '课程代码',
  `course_name` varchar(100) DEFAULT NULL COMMENT '课程名称',
  `semester` varchar(20) DEFAULT NULL COMMENT '学期',
  `experiment_type` varchar(20) DEFAULT NULL COMMENT '实验类型',
  `experiment_hours` int(11) DEFAULT NULL COMMENT '实验学时',
  `teacher_id` bigint(20) DEFAULT NULL COMMENT '教师ID',
  `teacher_name` varchar(50) DEFAULT NULL COMMENT '教师姓名',
  `dept_id` bigint(20) DEFAULT NULL COMMENT '院系ID',
  `objectives` text COMMENT '实验目的',
  `requirements` text COMMENT '实验要求',
  `equipment` text COMMENT '实验仪器设备',
  `materials` text COMMENT '实验材料',
  `procedure` text COMMENT '实验步骤',
  `precautions` text COMMENT '注意事项',
  `assessment_criteria` text COMMENT '考核标准',
  `status` tinyint(1) DEFAULT '0' COMMENT '状态：0-草稿，1-已完成',
  `creator` varchar(50) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(50) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_teacher_id` (`teacher_id`),
  KEY `idx_dept_id` (`dept_id`),
  KEY `idx_status` (`status`),
  KEY `idx_semester` (`semester`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='实验指导书表';

-- 教学成果表
CREATE TABLE IF NOT EXISTS `ed_teaching_achievement` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '成果ID',
  `name` varchar(200) NOT NULL COMMENT '成果名称',
  `category` varchar(50) DEFAULT NULL COMMENT '成果类别',
  `level` varchar(20) DEFAULT NULL COMMENT '成果级别',
  `course_id` bigint(20) DEFAULT NULL COMMENT '相关课程ID',
  `course_name` varchar(100) DEFAULT NULL COMMENT '相关课程名称',
  `teacher_id` bigint(20) DEFAULT NULL COMMENT '教师ID',
  `teacher_name` varchar(50) DEFAULT NULL COMMENT '教师姓名',
  `dept_id` bigint(20) DEFAULT NULL COMMENT '院系ID',
  `award_time` date DEFAULT NULL COMMENT '获奖时间',
  `award_unit` varchar(100) DEFAULT NULL COMMENT '授予单位',
  `award_certificate` varchar(500) DEFAULT NULL COMMENT '获奖证书',
  `description` text COMMENT '成果描述',
  `creator` varchar(50) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(50) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_teacher_id` (`teacher_id`),
  KEY `idx_dept_id` (`dept_id`),
  KEY `idx_category` (`category`),
  KEY `idx_level` (`level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='教学成果表';

-- 教学文档审批表
CREATE TABLE IF NOT EXISTS `ed_document_approval` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '审批ID',
  `doc_type` varchar(50) NOT NULL COMMENT '文档类型',
  `doc_id` bigint(20) NOT NULL COMMENT '文档ID',
  `workflow_inst_id` bigint(20) DEFAULT NULL COMMENT '工作流实例ID',
  `submit_user_id` bigint(20) DEFAULT NULL COMMENT '提交用户ID',
  `submit_time` datetime DEFAULT NULL COMMENT '提交时间',
  `current_approver` varchar(100) DEFAULT NULL COMMENT '当前审批人',
  `status` tinyint(1) DEFAULT '0' COMMENT '状态：0-待审批，1-审批中，2-已通过，3-已驳回',
  `result` tinyint(1) DEFAULT NULL COMMENT '结果：0-不通过，1-通过',
  `comment` text COMMENT '审批意见',
  `approve_time` datetime DEFAULT NULL COMMENT '审批时间',
  `creator` varchar(50) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(50) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_doc_id` (`doc_type`,`doc_id`),
  KEY `idx_workflow_inst_id` (`workflow_inst_id`),
  KEY `idx_submit_user_id` (`submit_user_id`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='教学文档审批表';

-- 文档完成度表
CREATE TABLE IF NOT EXISTS `ed_document_completion` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `semester` varchar(20) DEFAULT NULL COMMENT '学期',
  `teacher_id` bigint(20) DEFAULT NULL COMMENT '教师ID',
  `dept_id` bigint(20) DEFAULT NULL COMMENT '院系ID',
  `course_id` bigint(20) DEFAULT NULL COMMENT '课程ID',
  `doc_type` varchar(50) NOT NULL COMMENT '文档类型',
  `total_count` int(11) DEFAULT '0' COMMENT '应完成总数',
  `completed_count` int(11) DEFAULT '0' COMMENT '已完成数量',
  `completion_rate` decimal(5,2) DEFAULT '0.00' COMMENT '完成率',
  `deadline` datetime DEFAULT NULL COMMENT '截止时间',
  `status` tinyint(1) DEFAULT '0' COMMENT '状态：0-未完成，1-已完成，2-逾期',
  `remind_count` int(11) DEFAULT '0' COMMENT '提醒次数',
  `last_remind_time` datetime DEFAULT NULL COMMENT '最后提醒时间',
  `creator` varchar(50) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(50) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_teacher_id` (`teacher_id`),
  KEY `idx_dept_id` (`dept_id`),
  KEY `idx_semester` (`semester`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_doc_type` (`doc_type`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档完成度表';

-- 教学小结表
CREATE TABLE IF NOT EXISTS `ed_teaching_summary` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '小结ID',
  `course_id` bigint(20) NOT NULL COMMENT '课程ID',
  `course_code` varchar(50) DEFAULT NULL COMMENT '课程代码',
  `course_name` varchar(100) DEFAULT NULL COMMENT '课程名称',
  `semester` varchar(20) DEFAULT NULL COMMENT '学期',
  `teacher_id` bigint(20) DEFAULT NULL COMMENT '教师ID',
  `teacher_name` varchar(50) DEFAULT NULL COMMENT '教师姓名',
  `dept_id` bigint(20) DEFAULT NULL COMMENT '院系ID',
  `student_count` int(11) DEFAULT NULL COMMENT '学生人数',
  `pass_rate` decimal(5,2) DEFAULT NULL COMMENT '通过率',
  `excellent_rate` decimal(5,2) DEFAULT NULL COMMENT '优秀率',
  `teaching_methods` text COMMENT '教学方法总结',
  `teaching_effect` text COMMENT '教学效果总结',
  `problems` text COMMENT '存在问题',
  `improvement` text COMMENT '改进措施',
  `recommendations` text COMMENT '建议',
  `status` tinyint(1) DEFAULT '0' COMMENT '状态：0-草稿，1-已完成',
  `creator` varchar(50) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(50) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` tinyint(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
  PRIMARY KEY (`id`),
  KEY `idx_course_id` (`course_id`),
  KEY `idx_teacher_id` (`teacher_id`),
  KEY `idx_dept_id` (`dept_id`),
  KEY `idx_semester` (`semester`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='教学小结表'; 